[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@vercel/og/**/*"]

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200 