[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  included_files = ["node_modules/@vercel/og/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@vercel/og"]

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true 